name: roocswps
channels:
#- conda-forge
- defaults
dependencies:
- pip
- pywps=4.2
- jinja2
- click
- psutil
# tests
- pytest
#- pip:
#  - -e git+https://github.com/roocs/proto-lib-34e@master#egg=daops
