name: rook
channels:
- conda-forge
- defaults
dependencies:
#- python=3.7
- pip
- python>=3.6,<3.8
- pywps>=4.2.4,<4.3
- jinja2
- click
- psutil
# tests
- pytest
# daops
- udunits2>=2.2
- xarray>=0.15
- dask
- netcdf4
- clisops>=0.3.0,<0.4
# workflow
- networkx
# tests
- pytest
- pip:
  # - daops>=0.2.0<0.3
  - -e git+https://github.com/roocs/roocs-utils.git@implement-split-outputs#egg=roocs_utils
  - -e git+https://github.com/roocs/clisops.git@implement-split-outputs#egg=clisops
  - -e git+https://github.com/roocs/daops.git@implement_split_method#egg=daops
