# conda env update -f environment.yml
name: rook
channels:
  - conda-forge
dependencies:
  - pip
  - ipython
  - jupyterlab
  - ipywidgets
  - nodejs
  - birdy
  - pip:
    - -e git+https://github.com/cehbrecht/pymetalink.git@patched#egg=metalink
